{% set name = "tiktoken" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tiktoken-{{ version }}.tar.gz
  sha256: 7cd88c11699b18081822e6ae1beee55e8f20ea361d73c507d33f5a89a1898f1c

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools >=62.4
    - wheel
    - setuptools-rust >=1.5.2
    - pip
  run:
    - python
    - regex >=2022.1.18
    - requests >=2.26.0

test:
  imports:
    - tiktoken
    - tiktoken_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openai/tiktoken
  summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
