{% set name = "tiktoken" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiktoken-{{ version }}.tar.gz
  sha256: 8295912429374f5f3c6c6bf053a091ce1de8c1792a62e3b30d4ad36f47fa8b52

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools >=62.4
    - wheel
    - setuptools-rust >=1.5.2
    - pip
  run:
    - python
    - regex >=2022.1.18
    - requests >=2.26.0

test:
  imports:
    - tiktoken
    - tiktoken_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openai/tiktoken
  summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - BastianZim
